# Site settings
title: Shreya Chawla
general_email: shreyachawla1798@gmail.com
academic_email: shreya.chawla@anu.edu.au

description: > # this means to ignore newlines until "baseurl:"
  Master of Machine Learning and Computer Vision student at Australian National University interested in Computer Vision and its applications.

#baseurl: "/shreya888" # the subpath of your site, e.g. /blog/

url: "https://shreya888.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: shreya888
linkedin_username: shreyachawla1998
#facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
